package real;

import java.sql.Date;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class AddPaddyPanel extends javax.swing.JPanel {

    DAO dao;
    public AddPaddyPanel() {
        dao = new DAO();
        initComponents();
        GetFarmer();
        DisplayPaddy();
        
        
        JPanel panel = this;
        
       /* addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String farmerId = farmerIdField.getSelectedItem().toString();
                String quantity = quantityField.getText().toString();
                String dateofarrival = dateofarrivalField.getText().toString();
                String mositure = mositureField.getText().toString();
                String quality = qualityCombo.getSelectedItem().toString();
                String storage = storageField.getText().toString();
                
                if(farmerId.isEmpty() || quantity.isEmpty() || dateofarrival.isEmpty() || mositure.isEmpty() || storage.isEmpty()){
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Required field is empty",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if(dao.addPaddy(Integer.parseInt(farmerId),Double.parseDouble(quantity),Date.valueOf(dateofarrival),Double.parseDouble(mositure),quality,storage)){
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Succesfully added paddy",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Unknow error",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                }
            }
        });*/
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        mositureField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        qualityCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        storageField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        dateofarrivalField = new javax.swing.JTextField();
        farmerIdField = new javax.swing.JComboBox<>();
        clearButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paddyTable = new javax.swing.JTable();

        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FarmerID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Date of Arrival");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Moisture Level");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Quality");

        quantityField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        mositureField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        qualityCombo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        qualityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Very Good", "Good", "Bad", "Very Bad" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Storage");

        storageField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Add Paddy");

        updateButton.setBackground(new java.awt.Color(153, 255, 153));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        dateofarrivalField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        farmerIdField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        farmerIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmerIdFieldActionPerformed(evt);
            }
        });

        clearButton1.setBackground(new java.awt.Color(255, 102, 102));
        clearButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearButton1.setText("Clear");
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        paddyTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paddyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PaddyID", "FarmerID", "Quantity", "Date_of_Arrival", "Moisture_Level", "QualityParameters", "Storage_Location"
            }
        ));
        paddyTable.setToolTipText("");
        paddyTable.setAlignmentX(1.0F);
        paddyTable.setAlignmentY(1.0F);
        paddyTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        paddyTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        paddyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paddyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(paddyTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(quantityField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mositureField)
                            .addComponent(dateofarrivalField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(farmerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(storageField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qualityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(419, 419, 419)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qualityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(farmerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dateofarrivalField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(storageField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(86, 86, 86)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mositureField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Clear()
    {
        farmerIdField.setSelectedItem("");
        quantityField.setText("");
        dateofarrivalField.setText("");
        mositureField.setText("");
        storageField.setText("");
    }
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;
    private void GetFarmer()
    {
        try{
             Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
             St=Con.createStatement();
             String Query = "select * from Farmers";
             Rs=St.executeQuery(Query);
             while(Rs.next())
             {
                 String farmerId=String.valueOf(Rs.getInt("FarmerID"));
                 farmerIdField.addItem(farmerId);
             }
        }catch(Exception e){
            
        }
    }
    
    Connection Con1 = null;
    PreparedStatement pst1 = null;
    ResultSet Rs2 = null, Rs3 = null;
    Statement St2 = null, St3 = null;
    private void DisplayPaddy()
    {
        try{
            Con1 = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
            St2 = Con1.createStatement();
            Rs2 = St2.executeQuery("select * from Paddy");
            paddyTable.setModel(DbUtils.resultSetToTableModel(Rs2));
        }catch(Exception e){
            
        }
    }
       
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(quantityField.getText().isEmpty() || dateofarrivalField.getText().isEmpty() || mositureField.getText().isEmpty() || storageField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } 
        else 
        {
              try{
                        
                   Con1 = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                   PreparedStatement Add = Con1.prepareStatement("INSERT INTO paddy(FarmerID,Quantity,Date_of_Arrival,Moisture_Level,Quality_Parameters,Storage_Location) VALUES(?,?,?,?,?,?)");
                   Add.setString(1, farmerIdField.getSelectedItem().toString());
                   Add.setDouble(2, Double.valueOf(quantityField.getText()));
                   Add.setDate(3, Date.valueOf(dateofarrivalField.getText()));
                   Add.setDouble(4, Double.valueOf(mositureField.getText()));
                   Add.setString(5, qualityCombo.getSelectedItem().toString());
                   Add.setString(6, storageField.getText().toString());
                   
                   int row = Add.executeUpdate();
                   JOptionPane.showMessageDialog(this, "Paddy Added");
                   Con.close();
                   DisplayPaddy();
                   
              }catch(Exception e){
                   JOptionPane.showMessageDialog(this, e);
              }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
         if(Key=="")
        {
            JOptionPane.showMessageDialog(this, "Select a Paddy");
        } 
        else 
        {
              try{           
                   Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                   String Query = "Update Paddy set FarmerID=?,Quantity=?,Date_of_Arrival=?,Moisture_Level=?,Quality_Parameters=?,Storage_Location=? where PaddyId=?";
                   
                   PreparedStatement Add = Con1.prepareStatement(Query);
                   Add.setString(7,Key);
                   
                   Add.setString(1, farmerIdField.getSelectedItem().toString());
                   Add.setString(2, quantityField.getText().toString());
                   Add.setString(3, dateofarrivalField.getText().toString());
                   Add.setString(4, mositureField.getText().toString());
                   Add.setString(5, qualityCombo.getSelectedItem().toString());
                   Add.setString(6, storageField.getText().toString());
                   
                   int row = Add.executeUpdate();
                   JOptionPane.showMessageDialog(this, "Paddy Updated");
                   Con1.close();
                   DisplayPaddy();
                   Clear();
              }catch(Exception e){
                   JOptionPane.showMessageDialog(this, e);
              }
        }      
    }//GEN-LAST:event_updateButtonActionPerformed

    private void farmerIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmerIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_farmerIdFieldActionPerformed

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        Clear();
    }//GEN-LAST:event_clearButton1ActionPerformed
    
    String  Key= "";
    private void paddyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paddyTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)paddyTable.getModel();
        int MyIndex = paddyTable.getSelectedRow();
        Key =model.getValueAt(MyIndex, 0).toString();
        
        farmerIdField.setSelectedItem(model.getValueAt(MyIndex,1).toString());
        quantityField.setText(model.getValueAt(MyIndex,2).toString());
        dateofarrivalField.setText(model.getValueAt(MyIndex,3).toString()); 
        mositureField.setText(model.getValueAt(MyIndex,4).toString());
        qualityCombo.setSelectedItem(model.getValueAt(MyIndex,5).toString());
        storageField.setText(model.getValueAt(MyIndex,6).toString());
    }//GEN-LAST:event_paddyTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton1;
    private javax.swing.JTextField dateofarrivalField;
    private javax.swing.JComboBox<String> farmerIdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mositureField;
    private javax.swing.JTable paddyTable;
    private javax.swing.JComboBox<String> qualityCombo;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField storageField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
