package real;

import java.sql.Date;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class AddSalesPanel extends javax.swing.JPanel {

    DAO dao;
    public AddSalesPanel() {
        dao = new DAO();
        initComponents();
        GetShop();
        DisplaySales();
        
        JPanel panel = this;
        
        /*addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                String shopId = shopIdField.getSelectedItem().toString();
                String riceQuantity = riceQuantityField.getText().toString();
                String brokenRiceQuantity = brokenRiceQuantityField.getText().toString();
                String branQuantity = branQuantityField.getText().toString();
                String saleDate = saleDateField.getText().toString();
                
                if(shopId.isEmpty() || riceQuantity.isEmpty() || brokenRiceQuantity.isEmpty() || branQuantity.isEmpty() || saleDate.isEmpty()){
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Required field is empty",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(dao.addSales(Integer.parseInt(shopId),Double.parseDouble(riceQuantity),Double.parseDouble(brokenRiceQuantity),Double.parseDouble(branQuantity),Date.valueOf(saleDate))){
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Succesfully added to Sales",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Unknow error",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                }
                               
                
            }
        });*/
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        brokenRiceQuantityField = new javax.swing.JTextField();
        riceQuantityField = new javax.swing.JTextField();
        branQuantityField = new javax.swing.JTextField();
        saleDateField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        shopIdField = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        clearButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ShopID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Rice Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Broken Rice Quantity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Bran Quantity");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Sale Date");

        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Include Sales");

        brokenRiceQuantityField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        brokenRiceQuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brokenRiceQuantityFieldActionPerformed(evt);
            }
        });

        riceQuantityField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        riceQuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceQuantityFieldActionPerformed(evt);
            }
        });

        branQuantityField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        branQuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branQuantityFieldActionPerformed(evt);
            }
        });

        saleDateField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        saleDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleDateFieldActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(153, 255, 153));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        shopIdField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        salesTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SaleID", "ShopID", "Rice Quantity", "Broken Rice Quantity", "Bran Quantity", "Sale Date"
            }
        ));
        salesTable.setToolTipText("");
        salesTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salesTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salesTable);

        clearButton1.setBackground(new java.awt.Color(255, 102, 102));
        clearButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearButton1.setText("Clear");
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(riceQuantityField)
                            .addComponent(shopIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(branQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(saleDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(brokenRiceQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(382, 382, 382))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(updateButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(shopIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(riceQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(branQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brokenRiceQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Clear()
    {
        shopIdField.setSelectedItem("");
        riceQuantityField.setText("");
        brokenRiceQuantityField.setText("");
        branQuantityField.setText("");
        saleDateField.setText("");
    }
    
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;
    private void GetShop()
    {
        try{
             Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
             St=Con.createStatement();
             String Query = "select * from Shop";
             Rs=St.executeQuery(Query);
             while(Rs.next())
             {
                 String shopId=String.valueOf(Rs.getInt("ShopID"));
                 shopIdField.addItem(shopId);
             }
        }catch(Exception e){
            
        }
    }
    
    Connection Con1 = null;
    PreparedStatement pst1 = null;
    ResultSet Rs2 = null, Rs3 = null;
    Statement St2 = null, St3 = null;
    private void DisplaySales()
    {
        try{
            Con1 = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
            St2 = Con1.createStatement();
            Rs2 = St2.executeQuery("select * from Sales");
            salesTable.setModel(DbUtils.resultSetToTableModel(Rs2));
        }catch(Exception e){
            
        }
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(riceQuantityField.getText().isEmpty() || brokenRiceQuantityField.getText().isEmpty() || branQuantityField.getText().isEmpty() || saleDateField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } 
        else 
        {
              try{
                        
                   Con1 = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                   PreparedStatement Add = Con1.prepareStatement("INSERT INTO Sales(ShopID,Rice_Quantity,Broken_Rice_Quantity,Bran_Quantity,Sale_Date) VALUES(?,?,?,?,?)");
                   Add.setString(1, shopIdField.getSelectedItem().toString());
                   Add.setDouble(2, Double.valueOf(riceQuantityField.getText()));
                   Add.setDouble(3, Double.valueOf(brokenRiceQuantityField.getText()));
                   Add.setDouble(4, Double.valueOf(branQuantityField.getText()));
                   Add.setDate(5, Date.valueOf(saleDateField.getText()));
                   
                   
                   int row = Add.executeUpdate();
                   JOptionPane.showMessageDialog(this, "Sales Added");
                   Con.close();
                   DisplaySales();
                   
              }catch(Exception e){
                   JOptionPane.showMessageDialog(this, e);
              }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void brokenRiceQuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brokenRiceQuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brokenRiceQuantityFieldActionPerformed

    private void riceQuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceQuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceQuantityFieldActionPerformed

    private void branQuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branQuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branQuantityFieldActionPerformed

    private void saleDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleDateFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if(Key=="")
        {
            JOptionPane.showMessageDialog(this, "Select a Sale item");
        } 
        else 
        {
              try{           
                   Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                   String Query = "Update Sales set ShopID=?,Rice_Quantity=?,Broken_Rice_Quantity=?,Bran_Quantity=?,Sale_Date=? where SaleID=?";
                   
                   PreparedStatement Add = Con1.prepareStatement(Query);
                   Add.setString(6,Key);
                   
                   Add.setString(1, shopIdField.getSelectedItem().toString());
                   Add.setDouble(2, Double.valueOf(riceQuantityField.getText()));
                   Add.setDouble(3, Double.valueOf(brokenRiceQuantityField.getText()));
                   Add.setDouble(4, Double.valueOf(branQuantityField.getText()));
                   Add.setDate(5, Date.valueOf(saleDateField.getText()));
                   
                   
                   int row = Add.executeUpdate();
                   JOptionPane.showMessageDialog(this, "Sales Updated");
                   Con1.close();
                   DisplaySales();
                   Clear();
                   
              }catch(Exception e){
                   JOptionPane.showMessageDialog(this, e);
              }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        Clear();
    }//GEN-LAST:event_clearButton1ActionPerformed

    String  Key= "";
    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)salesTable.getModel();
        int MyIndex = salesTable.getSelectedRow();
        Key =model.getValueAt(MyIndex, 0).toString();
        
        shopIdField.setSelectedItem(model.getValueAt(MyIndex,1).toString());
        riceQuantityField.setText(model.getValueAt(MyIndex,2).toString());
        brokenRiceQuantityField.setText(model.getValueAt(MyIndex,3).toString()); 
        branQuantityField.setText(model.getValueAt(MyIndex,4).toString());
        saleDateField.setText(model.getValueAt(MyIndex,5).toString());
        
    }//GEN-LAST:event_salesTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField branQuantityField;
    private javax.swing.JTextField brokenRiceQuantityField;
    private javax.swing.JButton clearButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField riceQuantityField;
    private javax.swing.JTextField saleDateField;
    private javax.swing.JTable salesTable;
    private javax.swing.JComboBox<String> shopIdField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
