package real;

import java.sql.Date;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class AddShopPanel extends javax.swing.JPanel {

    DAO dao;
    public AddShopPanel() {
        dao = new DAO();
        initComponents();
        GetInventory();
        DisplayShop();
        
        JPanel panel = this;
        
        /*addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String inventoryId = inventoryIdField.getSelectedItem().toString();
                String name = nameField.getText().toString();
                String address = addressField.getText().toString();
                String contractNumber = contractNumberField.getText().toString();
                
                
                if(inventoryId.isEmpty() || name.isEmpty() || address.isEmpty() || contractNumber.isEmpty()){
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Required field is empty",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(dao.addShop(Integer.parseInt(inventoryId),name,address,contractNumber)){
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Succesfully added to Shop",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog((JFrame) SwingUtilities.getWindowAncestor(panel),
                    "Unknow error",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                }
                
                
                
            }
        });*/
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contractNumberField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        inventoryIdField = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        shopTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("InventoryID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Contract_Number");

        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Shop");

        contractNumberField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        contractNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractNumberFieldActionPerformed(evt);
            }
        });

        addressField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        nameField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 102, 102));
        clearButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        inventoryIdField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        shopTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ShopID", "InventoryID", "Name", "Address", "Contract Number"
            }
        ));
        shopTable.setToolTipText("");
        shopTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shopTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        shopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(shopTable);

        updateButton.setBackground(new java.awt.Color(153, 255, 153));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contractNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inventoryIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(clearButton)
                                .addGap(158, 158, 158)
                                .addComponent(updateButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inventoryIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contractNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Clear()
    {
        inventoryIdField.setSelectedItem("");
        nameField.setText("");
        addressField.setText("");
        contractNumberField.setText("");
    }
    
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;
    private void GetInventory()
    {
        try{
             Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
             St=Con.createStatement();
             String Query = "select * from Inventory";
             Rs=St.executeQuery(Query);
             while(Rs.next())
             {
                 String inventoryId=String.valueOf(Rs.getInt("InventoryID"));
                 inventoryIdField.addItem(inventoryId);
             }
        }catch(Exception e){
            
        }
    }
    
    Connection Con1 = null;
    PreparedStatement pst1 = null;
    ResultSet Rs2 = null, Rs3 = null;
    Statement St2 = null, St3 = null;
    private void DisplayShop()
    {
        try{
            Con1 = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
            St2 = Con1.createStatement();
            Rs2 = St2.executeQuery("select * from Shop");
            shopTable.setModel(DbUtils.resultSetToTableModel(Rs2));
        }catch(Exception e){
            
        }
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(nameField.getText().isEmpty() || addressField.getText().isEmpty() || contractNumberField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } 
        else 
        {
              try{
                        
                   Con1 = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                   PreparedStatement Add = Con1.prepareStatement("INSERT INTO Shop(InventoryID,Name,Address,Contract_Number) VALUES(?,?,?,?)");
                   Add.setString(1, inventoryIdField.getSelectedItem().toString());
                   Add.setString(2, nameField.getText().toString());
                   Add.setString(3, addressField.getText().toString());
                   Add.setString(4, contractNumberField.getText().toString());
                   
                   
                   int row = Add.executeUpdate();
                   JOptionPane.showMessageDialog(this, "Shop Item Added");
                   Con.close();
                   DisplayShop();
                   
              }catch(Exception e){
                   JOptionPane.showMessageDialog(this, e);
              }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void contractNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contractNumberFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        Clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
         if(Key=="")
        {
            JOptionPane.showMessageDialog(this, "Select a Shop Item");
        } 
        else 
        {
              try{           
                   Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                   String Query = "Update Shop set InventoryID=?,Name=?,Address=?,Contract_Number=? where ShopID=?";
                   
                   PreparedStatement Add = Con1.prepareStatement(Query);
                   Add.setString(5,Key);
                   
                   Add.setString(1, inventoryIdField.getSelectedItem().toString());
                   Add.setString(2, nameField.getText().toString());
                   Add.setString(3, addressField.getText().toString());
                   Add.setString(4, contractNumberField.getText().toString());
                   
                   
                   int row = Add.executeUpdate();
                   JOptionPane.showMessageDialog(this, "Shop Item Updated");
                   Con1.close();
                   DisplayShop();
                   Clear();
                   
              }catch(Exception e){
                   JOptionPane.showMessageDialog(this, e);
              }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    String  Key= "";
    private void shopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)shopTable.getModel();
        int MyIndex = shopTable.getSelectedRow();
        Key =model.getValueAt(MyIndex, 0).toString();
        
        inventoryIdField.setSelectedItem(model.getValueAt(MyIndex,1).toString());
        nameField.setText(model.getValueAt(MyIndex,2).toString());
        addressField.setText(model.getValueAt(MyIndex,3).toString()); 
        contractNumberField.setText(model.getValueAt(MyIndex,4).toString());
        
    }//GEN-LAST:event_shopTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField contractNumberField;
    private javax.swing.JComboBox<String> inventoryIdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTable shopTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
